# Generated by Django 2.2.5 on 2019-09-08 09:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(default='pics/gallery/default.jpg', upload_to='pics/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='pics/gallery/default.jpg', upload_to='pics/gallery')),
                ('description', ckeditor.fields.RichTextField()),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.event', verbose_name='Event')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
