# Generated by Django 2.2.3 on 2019-09-10 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 10, 10, 11, 19, 75547), verbose_name='date'),
        ),
    ]
