# Generated by Django 2.2.3 on 2019-09-16 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190910_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 11, 29, 0, 377352), verbose_name='date'),
        ),
    ]
