# Generated by Django 2.2.3 on 2019-09-17 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190916_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 17, 10, 34, 54, 726528), verbose_name='date'),
        ),
    ]
