# Generated by Django 2.2.5 on 2019-09-08 09:31

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 9, 8, 11, 31, 34, 917665), verbose_name='Date')),
                ('quote', ckeditor.fields.RichTextField()),
                ('book', models.CharField(max_length=100)),
                ('verse', models.IntegerField()),
                ('fro', models.IntegerField()),
                ('to', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quotes.event', verbose_name='Event')),
            ],
            options={
                'verbose_name_plural': 'Quotes',
            },
        ),
    ]
